on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Create local changes
      run: |
        cargo fmt
    - name: Commit files
      run: |
        git config --local user.email "eldon-chung@github.com"
        git config --local user.name "eldon-chung"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}