codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "50...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

ignore:
  - "**/*_tests.rs"       # wildcards accepted


coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 20%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced
        branches: 
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false

coverage:
  status:
    patch:
      default:
        # basic
        target: 10%
        threshold: 0%
        base: auto 
        # advanced
        branches: 
          - master
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: 
          - "unit"
        paths: 
          - "src"