language: rust
rust:
  - stable
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
script:
  - which cargo-make || cargo install cargo-make
  - cargo make ci-flow

env:
  global:
    - CARGO_MAKE_RUN_CODECOV="true"