language: rust

- name: Codecov
  uses: codecov/codecov-action@v1.0.7

- name: Coveralls GitHub Action
  uses: coverallsapp/github-action@v1.1.1


before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

matrix:
  include:
    - os: linux
      rust: nightly
    - os: linux
      rust: stable

script:
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        export CARGO_INCREMENTAL=0;
        export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort";
        export RUSTDOCFLAGS="-Cpanic=abort";
        cargo build --verbose $CARGO_OPTIONS;
        cargo test --verbose $CARGO_OPTIONS;
        zip -0 ccov.zip `find . \( -name "raccoon_editor*.gc*" \) -print`;
        ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
        ./grcov ccov.zip -s . -t coveralls --llvm --branch --ignore-not-existing --ignore "/*" --token jRSZlEVjkIYpYEeBNX1zDeEamjdfQxkw4 > coveralls.json;
        curl -S -F json_file=@coveralls.json https://coveralls.io/api/v1/jobs;
      fi
    - |
      if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then
          cargo build --verbose --all
          cargo test --verbose --all
      fi